### ISSUE TITLE
The app should not have a verified badge if it uses the name and the icon of another project

### ISSUE THREAD

**Issue by Jegah** [flathub/com.sudovanilla.penpot-desktop#3]
As the title says. This app uses the icon and the name of Penpot, while not being affiliated with the penpot project.
Having a verified badge while using someone else branding is extremely misleading. The app should either lose the verified badge, so not to imply being an official app or change its name and icon, making it obvious that this is a third app.

Otherwise this makes the verification system useless, as it is trivial to bypass.

**Comment by SudoVanilla** [comment]
We'll temporary remove the verified badge, but look into becoming official software for Penpot.
Major changes are planned for the software.

Thanks for noting this, as this could make a user thing it's official software without reading the description, I don't read it every time on apps anyway.

**Comment by SudoVanilla** [comment]
The app has been unverified in developer settings, this change should be visible next time Flathub.org updates.

**Comment by diacritica** [comment]
I, Pablo Ruiz-Múzquiz, CEO of Penpot, authorize Penpot Desktop unofficial app to be able to use Penpot’s trademark, including the company’s logo and name, for this desktop software. This permission requires that the Penpot Desktop expresses it is created as a Community Contribution and not by the Penpot core team, otherwise, we fully support this project and are happy to continue to sponsor its development.
